maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, 50)
basic.pause(2000)
maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CCW, 50)
maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CW, 50)
basic.pause(675)
maqueen.motorStop(maqueen.Motors.All)
maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, 50)
basic.pause(2000)
maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CCW, 50)
maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CW, 50)
basic.pause(675)
maqueen.motorStop(maqueen.Motors.All)
maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, 50)
basic.pause(2000)
maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CCW, 50)
maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CW, 50)
basic.pause(675)
maqueen.motorStop(maqueen.Motors.All)
maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, 50)
basic.pause(2000)
maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CCW, 50)
maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CW, 50)
basic.pause(675)
maqueen.motorStop(maqueen.Motors.All)
